---
title: "Roos Model in Ch7"
author: "Xianwen He"
date: "2023-02-22"
output: 
  prettydoc::html_pretty:
    toc: True
    theme: hpstr
    highlight: github
---

## Confirmatory Factor Analysis

### Factor Loading

```{r}
roos <- read.csv("./roos.csv")

CFAmodel <- '
PFact  =~ hotcore + earthsun + electron + radioact + lasers + condrift 
YEW    =~ bigbangrev + evolvedrev + condrift    
LSFact =~ boyorgrl + viruses + expdesgn + odds1 + odds2   

odds1 ~~ odds2
'
ordered  <- c(
  "expdesgn", "odds1", "odds2", "earthsun",
  "viruses", "condrift","radioact",
  "hotcore", "boyorgrl", "electron", 
  "lasers","evolvedrev", "bigbangrev"
)
```

Estimate using Lavaan with MLSMV.
```{r}
# lavaan
fit.lav <- lavaan::sem(
  CFAmodel,
  data = roos,
  ordered = ordered,
  estimator = "WLSMV"
)
(summ.lav <- lavaan::summary(fit.lav, fit.measures = TRUE, rsquare = TRUE))
```

SE for $R^2$.
```{r, warning=F, message=F}
library(dplyr)

rsq.mat <- summ.lav$pe %>% 
  dplyr::filter(op=='r2') %>% 
  dplyr::select(lhs, est) %>%
  dplyr::mutate(SE = 2/sqrt(nrow(roos))*est*(1-est^2))
colnames(rsq.mat) <- c('variable', 'R2', 'SE for R2')

rsq.mat
```


Calculate the proportion in the lowest category.
```{r}
threshold <- fit.lav@SampleStats@th[[1]]
threshold.label <- gsub('\\|t1', '', fit.lav@SampleStats@th.names[[1]])

num <- length(threshold)
portion <- sapply(1:num, function(i){
  tsd <- threshold[i]
  name <- threshold.label[i]
  clmn <- scale(roos[[name]])
  
  return(mean(clmn <= tsd))
})
names(portion) <- threshold.label

portion
```

Estimate using MIIVsem.
```{r}
fit.miiv <- MIIVsem::miive(CFAmodel, roos, var.cov=TRUE)
fit.miiv
```

### Correlation Matrix

```{r}
corr <- '
lasers ~~ hotcore + earthsun + electron + radioact +  condrift + bigbangrev + evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2 
hotcore ~~ + earthsun + electron + radioact +  condrift + bigbangrev + evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2
earthsun ~~ electron + radioact +  condrift + bigbangrev + evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2
electron ~~ radioact +  condrift + bigbangrev + evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2 
radioact ~~ condrift + bigbangrev + evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2
condrift ~~ bigbangrev + evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2 
bigbangrev ~~ evolvedrev + viruses + boyorgrl + expdesgn + odds1 + odds2 
evolvedrev ~~ viruses + boyorgrl + expdesgn + odds1 + odds2 
viruses ~~ boyorgrl + expdesgn + odds1 + odds2
boyorgrl ~~ expdesgn + odds1 + odds2
expdesgn ~~ odds1 + odds2
odds1 ~~ odds2
'
ordered  <- c(
  "expdesgn", "odds1", "odds2", "earthsun",
  "viruses", "condrift","radioact",
  "hotcore", "boyorgrl", "electron", 
  "lasers","evolvedrev", "bigbangrev"
)

fit.lav <- lavaan::sem(
  corr,
  data = roos,
  ordered = ordered,
  estimator = "WLSMV"
)
lavaan::summary(fit.lav, fit = TRUE, standardized = TRUE, rsq = TRUE)
```

## Observed Exogeneous Variables

Modify Roos' model by adding the following exogenous observed variables: education, age, sex, and race.

```{r}
ExogenX <- '
PFact  =~ hotcore + earthsun + electron + radioact + lasers + condrift 
YEW    =~ bigbangrev + evolvedrev + condrift    
LSFact =~ boyorgrl + viruses + expdesgn + odds1 + odds2
	
odds1 ~~ odds2
 
PFact  ~ educ + age + female + race_black + race_other + married
YEW    ~ educ + age + female + race_black + race_other + married
LSFact ~ educ + age + female + race_black + race_other + married
'
ordered  <- c(
  "expdesgn", "odds1", "odds2", "earthsun",
  "viruses", "condrift","radioact",
  "hotcore", "boyorgrl", "electron", 
  "lasers","evolvedrev", "bigbangrev"
)

# lavaan
fit.lav <- lavaan::sem(
  ExogenX,
  data = roos,
  ordered = ordered,
  estimator = "WLSMV"
)
lavaan::summary(fit.lav, fit = TRUE, standardized = TRUE, rsq = TRUE)
```

